# Generated by Django 4.1.2 on 2023-07-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_email',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
