# Generated by Django 4.1.2 on 2023-08-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_registered_email_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(default=False, verbose_name='take responsibility')),
                ('message', models.TextField()),
                ('person', models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50)),
                ('option', models.CharField(choices=[('My password does not work', 'My password does not work'), ('Update resume', 'Update resume'), ('Others', 'Others'), ('l lost my account', 'l lost my account')], max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Situation', models.CharField(choices=[('pending', 'pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True)),
            ],
        ),
    ]
