# Generated by Django 4.1.2 on 2023-08-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='support',
            name='Situation',
            field=models.CharField(choices=[('Done', 'Done'), ('pending', 'pending')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Others', 'Others'), ('My password does not work', 'My password does not work'), ('Update resume', 'Update resume'), ('l lost my account', 'l lost my account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate')], max_length=50),
        ),
    ]
