# Generated by Django 4.1.2 on 2023-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_created_at_support_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('l lost my account', 'l lost my account'), ('My password does not work', 'My password does not work'), ('Others', 'Others'), ('Update resume', 'Update resume')], max_length=50),
        ),
    ]
