# Generated by Django 4.1.2 on 2023-09-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_created_support_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Situation', models.CharField(choices=[('Done', 'Done'), ('pending', 'pending')], default='Pending', max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='Situation',
            field=models.CharField(choices=[('Done', 'Done'), ('pending', 'pending')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('l lost my account', 'l lost my account'), ('Others', 'Others'), ('My password does not work', 'My password does not work'), ('Update resume', 'Update resume')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50),
        ),
    ]
