# Generated by Django 4.1.2 on 2023-09-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_message_alter_support_situation_alter_support_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='Situation',
            field=models.CharField(choices=[('pending', 'pending'), ('Done', 'Done')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Update resume', 'Update resume'), ('My password does not work', 'My password does not work'), ('l lost my account', 'l lost my account'), ('Others', 'Others')], max_length=50),
        ),
    ]
