# Generated by Django 4.1.2 on 2023-09-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_message_situation_alter_support_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='Situation',
            field=models.CharField(choices=[('Done', 'Done'), ('pending', 'pending')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Update resume', 'Update resume'), ('Others', 'Others'), ('l lost my account', 'l lost my account'), ('My password does not work', 'My password does not work')], max_length=50),
        ),
    ]
