# Generated by Django 4.1.2 on 2023-10-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_notepad_alter_message_situation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('frontend', models.CharField(max_length=100)),
                ('backend', models.CharField(max_length=100)),
                ('fullstack', models.CharField(max_length=100)),
                ('intern', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='Situation',
            field=models.CharField(choices=[('Done', 'Done'), ('pending', 'pending')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Update resume', 'Update resume'), ('My password does not work', 'My password does not work'), ('l lost my account', 'l lost my account'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50),
        ),
    ]
