# Generated by Django 4.1.2 on 2023-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_vacancies_alter_message_situation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timer', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Update resume', 'Update resume'), ('l lost my account', 'l lost my account'), ('Others', 'Others'), ('My password does not work', 'My password does not work')], max_length=50),
        ),
    ]
