# Generated by Django 4.1.2 on 2023-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_countdown_alter_support_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='timer',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('My password does not work', 'My password does not work'), ('l lost my account', 'l lost my account'), ('Update resume', 'Update resume'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate')], max_length=50),
        ),
    ]
