# Generated by Django 4.1.2 on 2023-10-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_countdown_timer_alter_support_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='timer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('Update resume', 'Update resume'), ('My password does not work', 'My password does not work'), ('Others', 'Others'), ('l lost my account', 'l lost my account')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Employee', 'Employee')], max_length=50),
        ),
    ]
