# Generated by Django 4.1.2 on 2023-11-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_countdown_timer_alter_message_situation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Fullstack', 'Fullstack'), ('Intern', 'Intern')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('Situation', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_document', models.FileField(upload_to='')),
                ('company_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='Situation',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='option',
            field=models.CharField(choices=[('l lost my account', 'l lost my account'), ('Others', 'Others'), ('Update resume', 'Update resume'), ('My password does not work', 'My password does not work')], max_length=50),
        ),
        migrations.AlterField(
            model_name='support',
            name='person',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Candidate', 'Candidate')], max_length=50),
        ),
    ]
